### ISSUE TITLE
citi costco card

### ISSUE THREAD

**Issue by foosbar12** [clovett/MyMoney.Net#10]
Setting up Citi OFX server errors out during setup for me. The URL looks correct, and I'm getting a nonsense response from their server, so it's not a network error, but likely some configuration that I'm missing.

Is anyone successful in getting OFX data from Citi CC server? Anything in particular that I can do differently to finish the setup step successfully?

**Comment by clovett** [comment]
Yeah I got the same problem - started happening a few months ago, I called them, they said they "upgraded their servers" but refuse to give me the new OFX address :-(

**Comment by clovett** [comment]
You can export a QFX file from their website, look for the "Export" link and pick "Quicken" format, then import this file.  The account id might not match because they put XXXXX in it, so select the account and click import and it should be good.
