### ISSUE TITLE
copy and paste a transaction no longer works

### ISSUE THREAD

**Issue by andreva7** [clovett/MyMoney.Net#15]
Go to any account, type ctrl-C and ctrl-V and you get an error

![image](https://user-images.githubusercontent.com/37969784/59955769-1e152c80-9441-11e9-9fba-6958c4159b5c.png)

**Comment by clovett** [comment]
My bad, it’s fixed.  It’s an odd thing that can happen during deserialization of an object, the deserializer can set properties on the object before private fields have been initialized…

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by andreva7** [comment]
Thanks!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
