### ISSUE TITLE
password problem [?] on first use

### ISSUE THREAD

**Issue by the-wazz** [clovett/MyMoney.Net#2]
first-time user, ms installer.
when the program started and i was prompted to set up the db, i used a custom path/directory and included a password. the setup failed a couple of times. (sorry, didn't note the exact error msgs).

after the last attempt i did notice that part of the error msg included part of the password i used. the pw was created by a pw manager and i included special chars. i think that could have been the problem, or part of it. 

if there are restrictions on the pw they need to be mentioned during setup. if that's not a possible error i can try to recreate the problem again. let me know. i only finished the setup by leaving out the pw. (which is what lead to the other issue i filed, trying to rename the db in order to add a pw to it.)

**Comment by lovettchris** [comment]
thanks for the bug report.  There should be no special character restrictions on the password.  But I found the bug to do escaping special characters in your password.  This is fixed. You can also change the password on SQLite databases using View->Options.
