### ISSUE TITLE
Uncategorized transactions in cashflow

### ISSUE THREAD

**Issue by andreva7** [clovett/MyMoney.Net#26]
It would be useful to me if the cashflow report had another top level line that showed the total of the uncategorized amounts.
Right now it's hard to know how accurate the cashflow for a particular year is because the uncategorized transactions are not reflected anywhere.

**Comment by lovettchris** [comment]
Are they not showing up under 'Unknown' ?

**Comment by andreva7** [comment]
There is an unknow section when I look at the categories view.

There is no "unknown" section in the cashflow report though

***@***.***,
-Andre

**Comment by clovett** [comment]
I checked the cashflow report code and it definitely tallies uncategorized transactions:
```csharp
  else if (t.Category != null)
  {
      TallyCategory(t, t.Category, t, columnName, t.AmountMinusTax);
  }
  else if (t.Amount != 0)
  {
      TallyCategory(t, this.myMoney.Categories.Unknown, t, columnName, t.AmountMinusTax);
  }
```
And I see this in my reports, and when I click the Unknown line item I get a bunch of transactions with no categories.

**Comment by andreva7** [comment]
Sorry, I can't see it in the UI. Can you do a screenshot of where you are seeing it?

Thanks,

-Andre

**Comment by andreva7** [comment]
I did my first coding in here in a few years !😊 Only had to spend 45 minutes to update VS and the SDK ☹

In CashFlowReport.cs.

Adding

        private bool IsNone(Category c)
        {
            return (c.Type == CategoryType.None && c.ParentCategory == null);
        }

And
            GenerateGroup(writer, byCategory, columnTotals, "Uncategorized", (c) => { return IsNone(c); });

Makes the result show in the UI.  I don’t know if the name should be “uncategorized” or “none” or “unknown”.
We would need a bit more complicated code if you want that fourth line to only show up when there are some uncategorized entries in the time period.

-Andre

**Comment by clovett** [comment]
By the way @jpdup and I just finished a mamoth port of the UI themes to [ModernWPF](https://github.com/Kinnara/ModernWpf), this is included in https://github.com/clovett/MyMoney.Net/releases/tag/1.1.0.88 

For some screenshots see:
- https://github.com/clovett/MyMoney.Net/wiki
- the bottom of this page for the Dark theme: https://github.com/clovett/MyMoney.Net/wiki/Options

**Comment by clovett** [comment]
I think you had a screen shot but it didn't make it to github, can you try editing the above post on github to add the image?

**Comment by andreva7** [comment]
![image](https://user-images.githubusercontent.com/37969784/154766693-4126acfb-9ed7-4c7f-b317-bc9054a0d122.png)

**Comment by andreva7** [comment]
It looks like the default behavior when no category is specified for a transaction is to put it in Category type none, category unknown

![image](https://user-images.githubusercontent.com/37969784/154766895-5becbf44-e4d2-4e6c-af19-ed3f522053f3.png)

**Comment by lovettchris** [comment]
Ok, yes, this is a transaction without any category and it us "uncategorized" so it shows up when you select this right?
![image](https://user-images.githubusercontent.com/18707114/154767072-b6ab7878-bc27-4454-9136-fb6e0f416400.png)

And it should show up as "Unknown" expense on the cash flow report (since it is a payment, not a deposit).

But you could add a category named "Foo" and give it a CategoryType.None like this:

![image](https://user-images.githubusercontent.com/18707114/154767243-08aa6d30-7ff1-4ad3-a477-97ce1b1c5683.png)

And now this one will not appear in the cashflow report - so yes, there is a bug here.  But you can avoid this bug my ensuring you do not use "None" for the CategoryType.  I might actually remove it from the dialog and force you to pick a real category type...

**Comment by andreva7** [comment]
By default it does not show up in the cashflow report because the code does this:

            GenerateGroup(writer, byCategory, columnTotals, "Income", (c) => { return IsIncome(c); });

            GenerateGroup(writer, byCategory, columnTotals, "Expenses", (c) => { return IsExpense(c); });

            GenerateGroup(writer, byCategory, columnTotals, "Investments", (c) => { return IsInvestment(c); });

and the unknown category is not of type expense, it's of type none.

**Comment by clovett** [comment]
Hey love to know what you think about the new ModernWPF look, please be brutally honest, thanks.  We can easily tweak anything you don't like, so don't hold back.
