### ISSUE TITLE
Hitting an exception when trying to Rename a paye

### ISSUE THREAD

**Issue by mylojp** [clovett/MyMoney.Net#3]
![image](https://cloud.githubusercontent.com/assets/2709213/24088900/5190b5e4-0ced-11e7-8dd2-f5333ce367fe.png)

**Comment by clovett** [comment]
Oh, that’s bad.  I’ll check it out tomorrow sometime.

We should grab coffee and catch up – been way too long!

Had a fun day at my house flying drones with some friends from work today, super nice weather eh?

-Chris.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by joetossell29** [comment]
Thanks for releasing this guys. Hopefully I can finally get my house in order! Fixed the issue with the rename. See #4 Cheers.

**Comment by clovett** [comment]
Thanks for fixing this issue!

**Comment by mylojp** [comment]
Yes almost too hot of a day. Happy to have A.C.

On Mar 19, 2017, at 10:08 PM, clovett <notifications@github.com<mailto:notifications@github.com>> wrote:

Oh, that’s bad. I’ll check it out tomorrow sometime.

We should grab coffee and catch up – been way too long!

Had a fun day at my house flying drones with some friends from work today, super nice weather eh?

-Chris.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by clovett** [comment]
Me too.  I’ll have to turn on the sprinklers tonight…

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
