### ISSUE TITLE
Attach statement

### ISSUE THREAD

**Issue by andreva7** [clovett/MyMoney.Net#37]
I have a need to attach an official statement to a set of transactions.

If I take the example of credit cards, you want to keep the ability to attach an image of the receipt to a transaction.
At the end of the month, you want to download the PDF statement, and associate it to the 10 or 50 transactions that are covered by the statement.
When you go to court, people want to see the actual statement from the financial institution :-(

**Comment by lovettchris** [comment]
What do you think about adding an "Attachment" option to the "[Balancing Accounts](https://clovett.github.io/MyMoney.Net/#Accounts/BalancingAccounts/)" tab?

**Comment by andreva7** [comment]
That’s a cool idea for input!
Any thoughts on how to see the statement exists or not and then open it?

Sent from my Phone

On Mar 3, 2022, at 5:05 PM, Chris Lovett ***@***.***> wrote:

﻿

What do you think about adding an "Attachment" option to the "Balancing Accounts<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fclovett.github.io%2FMyMoney.Net%2F%23Accounts%2FBalancingAccounts%2F&data=04%7C01%7C%7C7b20067bc14a4046f6a308d9fd7b137f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637819527308530677%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=H4WRH19UUnemH02GYD5rFYth1bx6uYpHP0bGypY7lXk%3D&reserved=0>" tab?

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fclovett%2FMyMoney.Net%2Fissues%2F37%23issuecomment-1058723936&data=04%7C01%7C%7C7b20067bc14a4046f6a308d9fd7b137f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637819527308530677%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=vB1x7bAc9p5VA3xHRESn2Jl9Cy58LdnmP5%2BfvDYa1G4%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAJBV66DQLWO3P2TSUFEU7STU6FOVTANCNFSM5P3U75UQ&data=04%7C01%7C%7C7b20067bc14a4046f6a308d9fd7b137f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637819527308530677%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=zLVcT9e%2FEsMdGjLT9sMIeHdDXNM4zt3f8XXh6GKRUT4%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C7b20067bc14a4046f6a308d9fd7b137f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637819527308530677%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=3x1QgStaD6oHT9whV1gst0nT%2BLKCDwsPRWyone5XSqI%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C7b20067bc14a4046f6a308d9fd7b137f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637819527308530677%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=v5CTj5yJtnK%2FM6b4fxECXh%2Brg1ArvejgHfWwIVbGyI0%3D&reserved=0>.

**Comment by clovett** [comment]
This feature is now included in new version 2.0.0.4.
