### ISSUE TITLE
Fiscal year start setting is saved globally instead of per database

### ISSUE THREAD

**Issue by andreva7** [clovett/MyMoney.Net#38]
The fiscal year start setting is saved globally instead of per database.

**Comment by clovett** [comment]
ha, interesting...  it will take some work to implement this since I will need a new per-database setting concept...

**Comment by clovett** [comment]
Ok, I added a new xml settings file which lives next to your database like this:

![image](https://user-images.githubusercontent.com/3336415/187051825-5b6e07f5-93df-4d8e-b42d-6ace0b91beac.png)

And migrated FiscalYearStart and RentalManagement settings to this file out of the per user settings file.

This will be available in version 2.0.0.19.

**Comment by andreva7** [comment]
Cool - thanks!

**Comment by andreva7** [comment]
Thanks.
