### ISSUE TITLE
Default date for account balancing

### ISSUE THREAD

**Issue by andreva7** [clovett/MyMoney.Net#41]
When balancing an account, the default date used is 1 month after the previous balanced date.
I recommend special casing the end-of-month day
If the previous date is the last day of the month (Feb 28th for example) the default date for this month should be set to the last day of the month (March 31st).

**Comment by andreva7** [comment]
Still would be useful

**Comment by clovett** [comment]
This is checked in and will be bundled in the next release (2.0.0.11).  But it does have some weird edge cases.  For example, if you start with a statement date of "1/28/2022" then it will go to "2/28/2022" which is end of the month so the next date will be "3/31/2022", probably not what you expected.

**Comment by andreva7** [comment]
That will work great.
