### ISSUE TITLE
Balance account previous balance drop down bug

### ISSUE THREAD

**Issue by clovett** [clovett/MyMoney.Net#47]
OK, it reproed again.

Take an account that has been reconciled. In my case, one big reconcile from 2015 to 2020 when I looked at a 2020 statement.

Unreconcile that account by 
Ctrl-B on the account.
Going to the first transaction in the account (in 2015)
Flipping all transactions out of ‘R’ back to what it was (C, E, ‘ ‘)
Click cancel
->At this point all transactions are no longer marked reconcile.

Then start reconciling from 2015 (so I can add each monthly statement).

-Andre

From: Chris Lovett <[chris@lovettsoftware.com](mailto:chris@lovettsoftware.com)> 
Sent: April 1, 2022 12:16 AM
To: andre vachon <[andreva@outlook.com](mailto:andreva@outlook.com)>
Subject: RE: optimizing data entry

I’m not able to reproduce that with the latest bits?  Can you pull the latest bits, and/or check your index.xml file doesn’t have that bogus entry?

If you can provide steps that results in this additional entry let me know, but I’m not seeing anything obvious in the code…

From: andre vachon <[andreva@outlook.com](mailto:andreva@outlook.com)> 
Sent: Thursday, March 31, 2022 11:32 AM
To: Chris Lovett <[chris@lovettsoftware.com](mailto:chris@lovettsoftware.com)>
Subject: optimizing data entry

Is there a way to remove the bottom entry, which breaks the auto-date selection?

![image](https://user-images.githubusercontent.com/3336415/170847607-467a8bb0-edc5-4e9f-a292-6f84a8340aa6.png)

Thanks,

-Andre

**Comment by clovett** [comment]
Looking at the code, this would mean that the Account has a LastBalance set to 2020-12-08, but no transactions have this as their ReconciledDate, meaning there is no transactions that were marked as green during balancing where the statement date was set to 2020-12-08.  I removed the code that adds the Account.LastBalance to the list which might solve this problem. See commit https://github.com/clovett/MyMoney.Net/commit/f6f8d8b2d1b5126f9f117bf066539bc3d5f8dccf

**Comment by andreva7** [comment]
I unfortunately don't have the repro anymore.
