### ISSUE TITLE
Export no longer works

### ISSUE THREAD

**Issue by andreva7** [clovett/MyMoney.Net#52]
In the latest version I downloaded, 2.0.0.11, export on any account fails with 
![Screenshot 2022-08-05 144945](https://user-images.githubusercontent.com/37969784/183215495-1b063b5f-7bc4-462e-8aec-ff1ec33393e9.png)

**Comment by clovett** [comment]
I checked in a fix.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

From: ***@***.***>
Sent: Friday, August 5, 2022 2:50 PM
To: ***@***.***>
Cc: ***@***.***>
Subject: [clovett/MyMoney.Net] Export no longer works (Issue #52)


In the latest version I downloaded, 2.0.0.11, export on any account fails with
[Screenshot 2022-08-05 144945]<https://user-images.githubusercontent.com/37969784/183215495-1b063b5f-7bc4-462e-8aec-ff1ec33393e9.png>

**Comment by clovett** [comment]
Fixed in https://github.com/clovett/MyMoney.Net/commit/3525da65e5b4a9890c11752020712efe7ec5afb9

**Comment by clovett** [comment]
Fixed in 2.0.0.12
