### ISSUE TITLE
Balance column gone for stock accounts?

### ISSUE THREAD

**Issue by andreva7** [clovett/MyMoney.Net#55]
Is there a configuration parameter I changed somehow, or this this column get removed?

**Comment by lovettchris** [comment]
yes, it's gone because it gave the wrong impression, it was cash balance only which is confusing on an investment account.  The TrendGraph gives you the correct balance now.

**Comment by andreva7** [comment]
How would I track the cash balance on these accounts? Some are margin accounts, so the amount of debt in the account is really important.

**Comment by lovettchris** [comment]
sounds like you need it then, how about I put it back with the name "Cash Balance" ?

**Comment by clovett** [comment]
fixed in this branch: https://github.com/clovett/MyMoney.Net/commit/eb32db2e01128c18244fe853498a7fe35f2008fc

**Comment by andreva7** [comment]
That would be perfect.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
