### ISSUE TITLE
Net worth report pie chart

### ISSUE THREAD

**Issue by andreva7** [clovett/MyMoney.Net#57]
In the networth report, there is a pie chart.

improvement: You must use the pie chart to drill in - it would be nice to be able to click on the lines in the table format to drill in.

bug: in some cases, when you hover over a piece of the pie, it shows you information about the wrong piece. In the screen shot, when I hover over the green or teal sections, they both show me Cash, which is green. There is a tiny sliver of the teal section that will actually show me the right value
![pie](https://user-images.githubusercontent.com/37969784/184520822-aeb18272-742f-4400-9810-0166dff8ca4a.png)

**Comment by clovett** [comment]
Can you separate these into 2 issues? Thanks

**Comment by andreva7** [comment]
This is to track the "bug" only.

**Comment by andreva7** [comment]
Looking more at my chart, it's clearly related to negative numbers
Try creating this as a repro in the right account types:

Cash: $100
Investment Cash : $-50
Mutual Funds: $75

When I was trying to present the financial information to my lawyer, lines of credit \ margin was hard to represent. So I created a chart with absolute values, so large loans would also show up nicely, next to large investments. Might be an approach to use for this pie chart.

**Comment by clovett** [comment]
Ah, ok, yeah, negative values really make no sense in the pie chart, should I just remove them or should I take the absolute value?  Perhaps that would be too confusing...

**Comment by andreva7** [comment]
Well, net worth without taking into account debts is not net worth, so debts have to be there, which they are. The table form has the debts and liabilities, so the table is good.

The question is therefore simply about the pie chart itself.
The pie chart cant' be used to do any kind of math. In my opinion, it's just a glance view that lets you see the "big things". And a "big debt" is a "big thing", so I think it would be better to have the debts in the pie chart than have them just disappear.
So I think absolute value is the best approach.

Thinking of a very simple scenario: Someone has a $500K house and a $400K mortgage, $10K in the bank and $25K on credit cards. Just showing the $500K house and the $10K of cash seems like a misleading picture of one's networth.

**Comment by clovett** [comment]
Ok, I just pushed a change to add everything, using absolute value of liabilities.  It's a bit weird, might be better to split it into 2 pie charts Assets vs Liabilities...

**Comment by andreva7** [comment]
Looks better
