### ISSUE TITLE
Stock price can be wrong in networth report

### ISSUE THREAD

**Issue by andreva7** [clovett/MyMoney.Net#58]
When I set a past date in the net worth report, and then drill in to my mutual funds, the stock price of the stocks being displayed is often wrong or zero. If you expand a particular stock, then the stock price value is correct.

I think the overall value is correct, but I needed the price to validate that.

![stock price](https://user-images.githubusercontent.com/37969784/184520940-f17a7239-7a17-4c66-a5ac-2ab196ea6983.png)

**Comment by clovett** [comment]
I pushed a possible fix to the master branch.

**Comment by andreva7** [comment]
Looks good now! Thanks
