### ISSUE TITLE
historical net worth report - gain loss is wrong

### ISSUE THREAD

**Issue by andreva7** [clovett/MyMoney.Net#59]
When selecting a historical net worth view, and then drilling using the pie chart to some type of equity, the gain\loss column is not calculated correctly. This work fine when net worth is used for the current date
![gainloss](https://user-images.githubusercontent.com/37969784/184551921-941839e6-bea8-490c-9e56-0a7c27c848d7.png)

**Comment by clovett** [comment]
I pushed some fixes.

**Comment by andreva7** [comment]
Looks good. Thanks

**Comment by clovett** [comment]
Youre'welcome.  It is nice to have this historical view finally, thanks for pushing for it :-)
