### ISSUE TITLE
Feature request:: Show more context on Accounts and Payee view

### ISSUE THREAD

**Issue by lovettchris** [clovett/MyMoney.Net#6]
Adding a column in the Accounts panel that had “last transaction” for each of the accounts listed would give immediate context about which account is either not active or not recently updated.  In the payee view, the same column would be very interesting to see last time you made a payment to that payee.

The information about last transaction could be date/amount, perhaps always visible, or perhaps as a tooltip when you hover over the account/payee.

**Comment by andreva7** [comment]
The date of the last transaction gives you the important context of whether an account is active and\or updated.  When you have 50 accounts, its very valuable to know you may have missed getting data for a few of them.
All other values, whether the amount of category, etc don't help with that task.  You could also put the amount, but adding the amount without a payee is not useful.  IF the window now contained date, amount, payee, it becomes very big.  And the added context of the last transaction is not that useful.

Should the column be there all the time?
If it's just a date, it's not very wide so not very impactful to the overall UI.
Making it hideable would be ideal but creates more complexity in the UI.  You have to add a UI widget or menu that lets you enable\disable that column, which becomes one more feature in of itself.
If we really wanted the option of showing date and\or amount and\or payee, etc, then a configurable set of columns would make sense.

I would start with the simple approach - just the date - and then evaluate the user feedback about the need for more options.

**Comment by clovett** [comment]
I added last transaction details to the account view hover tooltip (version 1.1.17).
