### ISSUE TITLE
feature improvement: net worth drill-in to investments

### ISSUE THREAD

**Issue by andreva7** [clovett/MyMoney.Net#60]
Currently, you must use the pie chart to drill in to get details about securities. It would be nice to be able to click on the lines in the table format to drill in.

**Comment by clovett** [comment]
I added links on things you can drill into.  You currently can't drill into "cash" rows.  Let me know if you need that and what you would expect to see?  Perhaps totals by account or something?  

I also implemented reporting of the historical value of Loans.  So I can now see the amount I owed on my house years ago which is fun.

**Comment by andreva7** [comment]
For cash and credit, but most valuable for investment cash (because the account total is different than the Cash balance) total by account would be really good.

**Comment by clovett** [comment]
Ok, I added a drill down from networth report to see cash and investment cash balances totals by account. I also fixed another bug in account balance calculation (remove deleted and void transactions!) so the reports for today's date should match your account balances even better now.

**Comment by andreva7** [comment]
The drill down into the cash accounts, and especially investment cash accounts, is very nice. I unfortunately have 12 cash accounts and 15 investment accounts at this time, so this drill down gives a great view of where the money is.

-Andre

From: andre vachon
Sent: August 18, 2022 11:34 PM
To: clovett/MyMoney.Net ***@***.***>; clovett/MyMoney.Net ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [clovett/MyMoney.Net] feature improvement: net worth drill-in to investments (Issue #60)

You solved the 1 penny difference !!
The two numbers match now. Great job!

-Andre

**Comment by clovett** [comment]
Great do you consider this complete then?

**Comment by andreva7** [comment]
Done

**Comment by andreva7** [comment]
You solved the 1 penny difference !!
The two numbers match now. Great job!

-Andre
