### ISSUE TITLE
missing split in the UI

### ISSUE THREAD

**Issue by andreva7** [clovett/MyMoney.Net#66]
I bought some appl shares in 2012. When I look at AAPL in the View -> securities Window, it only shows me the stock split from 2014. The one from 2020 is missing.
When I look at my portfolio, I have the right number of shares, so internally it knows about the two stock splits.

**Comment by clovett** [comment]
You have to manually add stock split info using View/Securities view.  The "Add Sample Data" feature for new test databases adds it automatically for the 5 stocks that the sample database adds.

**Comment by andreva7** [comment]
OK
