### ISSUE TITLE
stock split handling in historical Net worth report

### ISSUE THREAD

**Issue by andreva7** [clovett/MyMoney.Net#67]
I bought AAPL stock in early 2012. When I do a net worth report for late 2012, it picks the right stock price for 2012, but the 2014 stock split is applied, which causes the total value of the stock in the report to be 7 times too high.

**Comment by clovett** [comment]
I have reproduced this bug, thanks.

**Comment by clovett** [comment]
Fixed in d0e273fb82a3489d677cc4edfcbf603b4bd6e21d

**Comment by andreva7** [comment]
Looks good
