### ISSUE TITLE
Starting balance included in historical net worth report

### ISSUE THREAD

**Issue by andreva7** [clovett/MyMoney.Net#68]
If you have an account with a negative opening balance (might be true for positive as well) and the first transaction for that account is in 2013, when you do a net worth report for 2012, that opening balance is included.
I would think the implicit date for the opening balance of an account should be the date of the first transaction.

**Comment by clovett** [comment]
ooo, that sounds like a bug...

**Comment by clovett** [comment]
Fix in commit 91de8a704c333b241ff112748f0742d6f7814d98

**Comment by andreva7** [comment]
Looks good!
