### ISSUE TITLE
IRA cash

### ISSUE THREAD

**Issue by andreva7** [clovett/MyMoney.Net#69]
I have some cash in my IRA. Under networth, that money gets lumped in with Investment cash (that break down of the cash is very useful!). Should there instead be a cash subsection under Tax-Deferred?

**Comment by clovett** [comment]
Sure thing, the networth report now breaks out "Cash", "Investment Cash" and optional "Tax-Deferred Cash" and "Tax-Free Cash" rows.  See https://github.com/clovett/MyMoney.Net/commit/18e2d0ada769080f3ac05df8ae913515562e5055

**Comment by andreva7** [comment]
Looks good. Thanks!
