### ISSUE TITLE
Typo in SQL INSERT for new accounts

### ISSUE THREAD

**Issue by joetossell29** [clovett/MyMoney.Net#7]
Typo in SQL INSERT for new accounts causing the insert to fail:
INSERT INTO Accounts (Id,AccountId,**OfxAccountId.Name**,Type,Description,OnlineAccount,OpeningBalance,LastSync,LastBalance,SyncGuid,Flags,Currency,WebSite,ReconcileWarning,CategoryIdForPrincipal,CategoryIdForInterest)

**Comment by clovett** [comment]
Thanks for the fix!
