### ISSUE TITLE
negative values in net worth report

### ISSUE THREAD

**Issue by andreva7** [clovett/MyMoney.Net#71]
I still like the pie chart using absolute values to measure the size of the pie slices.
A little nit: it would be great if when hovering over a slice of pie, it showed the original signed value, not the absolute value.

**Comment by clovett** [comment]
good idea!

**Comment by clovett** [comment]
Fixed in https://github.com/clovett/MyMoney.Net/commit/ad84d5af3128d11fc6cde01a296316d98a3232a3

**Comment by andreva7** [comment]
Looks great!
