### ISSUE TITLE
Rename account with linked statement for multiple accounts

### ISSUE THREAD

**Issue by andreva7** [clovett/MyMoney.Net#72]
I have account A and attached a statement to it.
The statement was for two accounts, so I went to account B and linked the statement. It looks like the file was single instanced and there was no mymoney.Statements\B directory created, no index. file.
I renamed account A to something else and the statement directory for that account got renamed as well.
The linking of the statement for account B broke.

Single instancing can be a cool feature, but in my case, where I need to present the raw statements as the source of truth (without mymoney on top of it), single instancing is actually a problem.

Single instance saves some space, but creates complexity in the code and weirdness in the data if you search for it. What about removing single instancing and just keep multiple copies if it gets linked from multiple accounts? A bit more space on disk (cheap these days), but these statements don't affect perf (they are loaded individually on demand), they already take a bunch of space (generally 100K, can be 500K each), and multi account statements of somewhat rare (for me at least)

**Comment by clovett** [comment]
ha ha, great bug, thanks.  Referential integrity is why god invented SQL :-)

**Comment by clovett** [comment]
Fixed by https://github.com/clovett/MyMoney.Net/commit/a18bcaca6800aa6dfd02f90bd72d656283622bc3
