### ISSUE TITLE
category move 

### ISSUE THREAD

**Issue by andreva7** [clovett/MyMoney.Net#79]
Under investments, I have a category called investment and a subcategory Dividends
I would like to move Dividends to be a top level category, but can't find a way.
Dragging in the UI does not appear to work, and using properties, trying to edit the category does not work.
Any thoughts?

**Comment by jpdup** [comment]
Here's one way to achieve your goal.

1. Create a new top level Category call "Foo"
2. While holding down the CTRL key drag the existing Dividends sub category to the Foo
3. This will merge the content of Dividends into Foo
4. Then rename Foo to whatever works or you

**Comment by andreva7** [comment]
Its working great. Thanks!
